[package]
name = "rust-yang"
version = "0.1.0"
authors = ["Ivaylo Petrov <ivajloip@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"

[dependencies.nom]
version = "4.2.2"
features = ["regexp", "regexp_macros"]
